name: CI
on: [push]

jobs:
  example:
    runs-on: [ubuntu-latest]
    env:
      input: environment variable
    steps:
    # use env variable as input
    - uses: actions/hello-world-javascript-action@master
      with:
          who-to-greet: ${{ env.input }}

    # use input from the github context[https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) - uses: actions/hello-world-javascript-action@master
      with:
          who-to-greet: ${{ github.repository}}

    - uses: actions/hello-world-javascript-action@master
      with:
          who-to-greet: ${{ github.ref }}
