on: push
jobs:
   deployment:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
        
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.3.1
        with:
         url: 'http://13.89.226.45:9090/stargazer/api/applications/get'
         method: 'GET'
         username: 'nikhar'
         password: 'Nikki@123'
         bearerToken: ${{ secrets.Bearertoken }}

      - name: Wait For HTTP Responses
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
        # URL to poll
         url: http://13.89.226.45:9090
        
        
