on: push
jobs:
   deployment:
     runs-on: ubuntu-latest
     steps:
      - name: CURL-ACTION
        uses: enflo/curl-action@v1.2
        with:
        # curl arguments
         curl: 'http://13.89.226.45:9090/stargazer/api/applications/get -H "Content-Type: application/json" -H “Authorization: Bearer ${{ secrets.Bearertoken }}”'
