on: push
jobs:
   deployment:
     runs-on: self-hosted
     steps:
      - name: cURL AxiosJS
        uses: indiesdev/curl@v1
        with:
         # The target url
         url: http://13.89.226.45:9090/stargazer/user/signup
        # The request method, basically one of GET, POST, PUT, PATCH
         method: POST
        # Body object
         body: username=xyz&password=Nikki@123&confirmPassword=Nikki@123
