on: push
jobs:
   deployment:
     runs-on: self-hosted
     steps:
     - name: CURL-ACTION
       uses: enflo/curl-action@v1.2
       with:
        # curl argument
         curl: 'http://13.89.226.45:9090/stargazer'
