on: push
jobs:
   deployment:
     runs-on: self-hosted
     steps:
      - name: cURL AxiosJS
        uses: satak/webrequest-action@master
        with:
    # The target url
         url: 'http://13.89.226.45:9090/stargazer/api/applications/get'
    # The request method, basically one of GET, POST, PUT, PATCH
         method: GET
    # Bearer Token
         auth: ${{ secrets.Bearertoken }}
     
        
    
 
