on: push
jobs:
   deployment:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.3.1
      - with:
         url: 'https://hub.docker.com/'
         method: 'GET'
         username: 'nikhae'
         password: ${{ secrets.Docker_Hub_Password }}
