on: push
jobs:
   deployment:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
        
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.3.1
        with:
         url: 'https://hub.docker.com/'
         method: 'GET'
         username: 'nikhar'
         password: ${{ secrets.Docker_Hub_Password }}

      - name: Wait For HTTP Responses
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
        # URL to poll
         url: https://hub.docker.com/
        
