name: CI
on: [push]

jobs:
 build-and-run:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - name: Build Code
    run: make Hello.java
  - name: run
    run: java Hello
  - uses: actions/upload-artifact@master
    with:
     # Artifact name
     name: Hello
     # what to upload
     path: gitactions
