name: CI
on: [push]

jobs:
 build-and-run:
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v1
    
  - name: Build Code
    run: make Hello.java
    
  - name: run
    run: java Hello
   
  - name: SAST-scan 
    uses: AppThreat/sast-scan-action@1.0.2
    with:
       output: sast-reports
       type: java
      
  - name: SAST scan succeeded
    if: success()
    run: echo 'SAST scan succeeded'
   
       
  - name: SAST scan failed
    if: failure()
    run: echo 'SAST scan failed'
    
   # upload artifact
  - name: SAST scan report
    if: always()
    uses: actions/upload-artifact@v1.0.0
    with:
        name: sast-reports
        path: sast-reports   
       
  - name: Build and push Docker images
    uses: docker/build-push-action@v1.1.0
    with:
       username: nikharmehta
       password: secrets.Docker_Hub_Password
       repository: docker_1
       path: https://hub.docker.com/_/jenkins
       target: build
       push: true
       
 
