name: CI
on: [push]

jobs:
 build-and-run:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - name: Build Code
    run: make Hello.java
  - name: run
    run: java Hello
  - name: Checkout
    uses: actions/checkout@v1
  - name: Checkmarx Action
    uses: checkmarx-ts/checkmarx-github-action@<version>
    with:
        cxServer: https://checkmarx.company.com
        cxUsername: First.Last@company.com
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: \CxServer\SP\Company\TeamA
