name: CI
on: [push]

jobs:
 build-and-run:
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v1
    
  - name: Build Code
    run: make Hello.java
    
  - name: run
    run: java Hello
   
  - name: SAST-scan 
    uses: AppThreat/sast-scan-action@1.0.2
    with:
       output: sast-reports
       type: java
   
 
